spring:
  application:
    name: shier-user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session登录态超时时间
  session:
    timeout: 86400
server:
  port: 8081
  servlet:
    context-path: /api
knife4j:
  enable: true
# 自动转换为驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)